import{test} from '@playwright/test'
test('Validate dropdown', async({page})=>{
    await page.goto('https://testautomationpractice.blogspot.com/')
    await page.locator('//input[@id="name"]').fill('Hari')
    await page.locator('//input[@id="email"]').fill('hari123@gmail.com')
    await page.locator('//input[@id="phone"]').fill('9876543210')
    await page.locator('//textarea[@id="textarea"]').fill('3street mtroad chennai')
    await page.locator('//input[@id="male"]').click()
    await page.locator('//input[@id="monday"]').check()
    await page.locator('//input[@id="wednesday"]').check()
    await page.locator('//input[@id="friday"]').check()
    const country= await page.locator('//select[@id="country"]')
    await country.selectOption({label:"India"})
    const countryTxt= await country.locator('option:checked').textContent()
    console.log('Selected country:', countryTxt)
    const colors= await page.locator('//select[@id="colors"]')
    await colors.selectOption([{index:0}, {value:"green"}, {label:"White"}])
    const colorsTxt= await colors.locator('option:checked').allTextContents()
    console.log('Selected colors:', colorsTxt)
    await page.waitForTimeout(3000)
})